name: Release NodeJS app

on:
  push:
    branches:
      - main

jobs:

  publish-docker-hub:
    name: Publish image to Docker Hub
    runs-on: ubuntu-latest
    steps:

    #step1
    - uses: actions/checkout@v3

    #step2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    #step3
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: dockermann1/express_app
