version: '3.8'

services:
    frontend:
      image: dockermann1/express_app
      ports:
        - 8080:8080
    watchtower:
      image: containrrr/watchtower
      environment:
        -  WATCHTOWER_POLL_INTERVAL=30 # Poll every 30 seconds
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
